@baseUrl = http://localhost:5000


################################################## Checklists
DELETE {{baseUrl}}/Checklists?id=1
#####
GET {{baseUrl}}/Checklists
#####
GET {{baseUrl}}/Checklists/1
#####
POST {{baseUrl}}/Checklists
Content-type: application/json

{
   "customerName": "abc"
}
#####
PUT {{baseUrl}}/Checklists
Content-type: application/json

{
   "id": 1,
   "customerName": "abc",
   "steps": 
   [{
      "id": 1,
      "stepNumber": 1,
      "stepDescription": "abc",
      "stepName": "abc",
      "stepChecklists": 
      [{
         "id": 1,
         "checklistId": 1,
         "stepId": 1,
         "checklist": 
         {
            "id": 1,
            "customerName": "abc",
            "orders": 
            [],
            "stepChecklists": 
            []
         },
         "step": 
         {
            "id": 1,
            "stepNumber": 1,
            "stepDescription": "abc",
            "stepName": "abc",
            "stepChecklists": 
            []
         }
      }]
   }]
}
#####

################################################## Conversations
DELETE {{baseUrl}}/Conversations?id=1
#####
GET {{baseUrl}}/Conversations?id=1
#####
GET {{baseUrl}}/Conversations/1
#####
POST {{baseUrl}}/Conversations?id=1
#####

################################################## Csinquiries
DELETE {{baseUrl}}/Csinquiries?id=1
#####
GET {{baseUrl}}/Csinquiries
#####
GET {{baseUrl}}/Csinquiries/1
#####
POST {{baseUrl}}/Csinquiries
Content-type: application/json

{
   "container": "abc",
   "fastLine": "abc",
   "directLine": "abc",
   "articleNumber": "abc",
   "palletamount": 1,
   "customer": "abc",
   "abnumber": 1,
   "bruttoWeightInKg": 1,
   "incoterm": "abc",
   "containersizeA": 1,
   "containersizeB": 1,
   "containersizeHc": 1,
   "freeDetention": True,
   "thctb": True,
   "readyToLoad": "abc",
   "loadingPlattform": "abc"
}
#####
PUT {{baseUrl}}/Csinquiries
Content-type: application/json

{
   "id": 1,
   "container": "abc",
   "fastLine": "abc",
   "directLine": "abc",
   "articleNumber": "abc",
   "palletamount": 1,
   "customer": "abc",
   "abnumber": 1,
   "bruttoWeightInKg": 1,
   "incoterm": "abc",
   "containersizeA": 1,
   "containersizeB": 1,
   "containersizeHc": 1,
   "freeDetention": True,
   "thctb": True,
   "readyToLoad": "abc",
   "loadingPlattform": "abc"
}
#####

################################################## Files
GET {{baseUrl}}/Files
#####
POST {{baseUrl}}/Files
Content-type: application/json

{
   "path": "abc"
}
#####

################################################## MessageConversations
GET {{baseUrl}}/MessageConversations
#####
GET {{baseUrl}}/MessageConversations/1
#####
POST {{baseUrl}}/MessageConversations
Content-type: application/json

{
   "conversationId": 1,
   "messageId": 1
}
#####

################################################## Messages
GET {{baseUrl}}/Messages?id=1
#####
POST {{baseUrl}}/Messages
Content-type: application/json

{
   "content": "abc",
   "attachmentId": 1
}
#####

################################################## Orders
DELETE {{baseUrl}}/Orders?id=1
#####
GET {{baseUrl}}/Orders
#####
GET {{baseUrl}}/Orders/1
#####
GET {{baseUrl}}/Orders/Amount?amout=1
#####
GET {{baseUrl}}/Orders/Approved?approved=True
#####
GET {{baseUrl}}/Orders/CreatedBy?createdBy=abc
#####
GET {{baseUrl}}/Orders/Customername?customername=abc
#####
GET {{baseUrl}}/Orders/Status?status=1
#####
POST {{baseUrl}}/Orders
Content-type: application/json

{
   "status": 1,
   "customerName": "abc",
   "createdBy": "abc",
   "amount": 1,
   "checklistId": 1,
   "csid": 1,
   "tlid": 1
}
#####
PUT {{baseUrl}}/Orders
Content-type: application/json

{
   "id": 1,
   "status": 1,
   "customerName": "abc",
   "createdBy": "abc",
   "approved": True,
   "amount": 1,
   "checklistId": 1
}
#####

################################################## StepChecklists
GET {{baseUrl}}/StepChecklists
#####

################################################## Steps
GET {{baseUrl}}/Steps/1
#####
POST {{baseUrl}}/Steps
Content-type: application/json

{
   "stepNumber": 1,
   "checklistId": 1,
   "stepDescription": "abc",
   "stepName": "abc"
}
#####

################################################## Tlinquiries
DELETE {{baseUrl}}/Tlinquiries?id=1
#####
GET {{baseUrl}}/Tlinquiries
#####
GET {{baseUrl}}/Tlinquiries/1
#####
POST {{baseUrl}}/Tlinquiries
Content-type: application/json

{
   "inquiryNumber": 1,
   "sped": "abc",
   "country": "abc",
   "acceptingPort": "abc",
   "expectedRetrieveWeek": "abc",
   "weightInKg": 1,
   "invoiceOn": "abc",
   "retrieveDate": "abc",
   "isContainer40": True,
   "isContainerHc": True,
   "retrieveLocation": "abc",
   "debtCapitalGeneralForerunEur": 1,
   "debtCapitalMainDol": 1,
   "debtCapitalTrailingDol": 1,
   "portOfDeparture": "abc",
   "ets": "abc",
   "eta": "abc",
   "boat": "abc"
}
#####
PUT {{baseUrl}}/Tlinquiries
Content-type: application/json

{
   "id": 1,
   "inquiryNumber": 1,
   "sped": "abc",
   "country": "abc",
   "acceptingPort": "abc",
   "expectedRetrieveWeek": "abc",
   "weightInKg": 1,
   "invoiceOn": "abc",
   "retrieveDate": "abc",
   "isContainer40": True,
   "isContainerHc": True,
   "retrieveLocation": "abc",
   "debtCapitalGeneralForerunEur": 1,
   "debtCapitalMainDol": 1,
   "debtCapitalTrailingDol": 1,
   "portOfDeparture": "abc",
   "ets": "abc",
   "eta": "abc",
   "boat": "abc"
}
#####
